version: "3.9"

services:

  webots:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: webots_simulation
    command: $WEBOTS
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    devices:
      - /dev/snd
      - /dev/dri
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=$XAUTH
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      $PORT:$PORT
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - $XAUTH:$XAUTH
      - $PORT_VOLUME

  theia:
    image: joachimhgg/theiatest:test1
    ports:
      - 3000:3000
