version: "3.7"

services:

  webots:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_PATH: $PROJECT_PATH
    command: $WEBOTS
    container_name: webots
    deploy:
      ports:
        - $PORT:$PORT
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    environment:
      - DISPLAY=$DISPLAY
      #- XAUTHORITY=$XAUTH
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      #- $XAUTH:$XAUTH
      - $PORT_VOLUME

  #theia:
  #  image: joachimhgg/theiatest:test1
  #  ports:
  #    - 3000:3000
